/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutAnimate: typeof import('@nutui/nutui-taro')['Animate']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutNotify: typeof import('@nutui/nutui-taro')['Notify']
    NutStep: typeof import('@nutui/nutui-taro')['Step']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
  }
}
